[project]
name = "score-analysis-project-qas-tactics"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "numpy (>=2.3.5,<3.0.0)"
]

[tool.poetry]
packages = [{include = "score_analysis_project", from = "src"}]

[tool.poetry.scripts]
score-analysis-project-qas-tactics = "score_analysis_project.main:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
