[project]
name = "foundational-semantic-model-generator"
version = "0.1.0"
description = ""
authors = [
    { name = "Your Name", email = "you@example.com" }
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "rdflib>=6.2.0,<8.0.0",
    "pandas (>=2.3.3,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]


[tool.poetry]
packages = [{ include = "foundational_semantic_model_generator", from = "src" }]

[tool.poetry.scripts]
foundational-semantic-model-generator = "foundational_semantic_model_generator.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
